language: en-US
tone_instructions: "Generate concise, actionable, and unambiguous fix instructions. Specify exact file paths and edits; focus on mechanical details required for automated or manual application. Focus on critical issues only."
reviews:
  profile: assertive
  commit_status: true
  fail_commit_status: true
  auto_review:
    enabled: true
    drafts: false
    branches:
      - main
      - dev
      - release/*
  tools:
    # Rust tooling
    clippy:
      enabled: true
      config_file: sea-core/Cargo.toml
    rustfmt:
      enabled: true
      config_file: .rustfmt.toml
    # Python tooling
    ruff:
      enabled: true
      config_file: pyproject.toml
knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "docs/**/*.md"
      - "sea-core/**/*.rs"
      - "sea-core/**/*.py"
      - "tests/**/*.rs"
      - "tests/**/*.py"
