module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-empty': [2, 'never'],
    'scope-enum': [
      2,
      'always',
      [
        'sea-core',
        'sea-dsl',
        'sea',
        'ci',
        'deps',
        'repo',
        'bindings',
        'calm',
        'cli',
        'code',
        'core',
        'docs',
        'format',
        'grammar',
        'graph',
        'new_docs',
        'parser',
        'pkg',
        'pyo3',
        'policy',
        'python',
        'registry',
        'release',
        'semantic-pack',
        'authority',
        'test',
        'tests',
        'units',
        'wasm',
      ],
    ],
  },
};

