/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum AggregateFunction {
  Count = 0,
  Sum = 1,
  Min = 2,
  Max = 3,
  Avg = 4
}
export const enum BinaryOp {
  And = 0,
  Or = 1,
  Equal = 2,
  NotEqual = 3,
  GreaterThan = 4,
  LessThan = 5,
  GreaterThanOrEqual = 6,
  LessThanOrEqual = 7,
  Plus = 8,
  Minus = 9,
  Multiply = 10,
  Divide = 11,
  Contains = 12,
  StartsWith = 13,
  EndsWith = 14,
  HasRole = 15,
  Before = 16,
  After = 17,
  During = 18
}
/** Severity level for policy violations */
export const enum Severity {
  Error = 0,
  Warning = 1,
  Info = 2
}
/** A policy violation */
export interface Violation {
  name: string
  message: string
  severity: Severity
}
/** Result of evaluating a policy against a graph */
export interface EvaluationResult {
  /** Backwards compatible boolean: false if evaluation is unknown (NULL) */
  isSatisfied: boolean
  /** Tri-state evaluation result: true, false, or null (NULL) */
  isSatisfiedTristate?: boolean
  /** List of violations */
  violations: Array<Violation>
}
export declare class Graph {
  constructor()
  addEntity(entity: Entity): void
  addResource(resource: Resource): void
  addFlow(flow: Flow): void
  addInstance(instance: ResourceInstance): void
  addRole(role: Role): void
  addRelation(relation: Relation): void
  entityCount(): number
  resourceCount(): number
  flowCount(): number
  instanceCount(): number
  patternCount(): number
  roleCount(): number
  relationCount(): number
  hasEntity(id: string): boolean
  hasResource(id: string): boolean
  hasFlow(id: string): boolean
  hasInstance(id: string): boolean
  getEntity(id: string): Entity | null
  getResource(id: string): Resource | null
  getFlow(id: string): Flow | null
  getInstance(id: string): ResourceInstance | null
  findRoleByName(name: string): string | null
  findEntityByName(name: string): string | null
  findResourceByName(name: string): string | null
  flowsFrom(entityId: string): Array<Flow>
  flowsTo(entityId: string): Array<Flow>
  allEntities(): Array<Entity>
  allResources(): Array<Resource>
  allFlows(): Array<Flow>
  allInstances(): Array<ResourceInstance>
  allRoles(): Array<Role>
  allRelations(): Array<Relation>
  static parse(source: string): Graph
  exportCalm(): string
  static importCalm(calmJson: string): Graph
  addPolicy(policyJson: string): void
  addAssociation(owner: string, owned: string, relType: string): void
  /**
   * Evaluate a Policy JSON payload against this Graph.
   *
   * The `policy_json` argument must be the JSON representation of `crate::policy::Policy`
   * (including fields like `id`, `name`, `modality`, `kind`, `version`, and `expression`).
   * Returns `EvaluationResult` exposed to TypeScript via napi, or an error if the policy JSON
   * is invalid or evaluation fails.
   */
  evaluatePolicy(policyJson: string): EvaluationResult
  /**
   * Set the evaluation mode for policy evaluation.
   * When `useThreeValuedLogic` is true, policies will use three-valued logic (true, false, null).
   * When false, policies will use strict boolean logic (true, false).
   */
  setEvaluationMode(useThreeValuedLogic: boolean): void
  /**
   * Get the current evaluation mode.
   * Returns true if three-valued logic is enabled, false otherwise.
   */
  useThreeValuedLogic(): boolean
  toString(): string
}
export declare class Entity {
  constructor(name: string, namespace?: string | undefined | null)
  get id(): string
  get name(): string
  get namespace(): string | null
  setAttribute(key: string, valueJson: string): void
  getAttribute(key: string): string | null
  toString(): string
}
export declare class Resource {
  constructor(name: string, unit: string, namespace?: string | undefined | null)
  get id(): string
  get name(): string
  get unit(): string
  get namespace(): string | null
  setAttribute(key: string, valueJson: string): void
  getAttribute(key: string): string | null
  toString(): string
}
export declare class Flow {
  constructor(resourceId: string, fromId: string, toId: string, quantity: number)
  get id(): string
  get resourceId(): string
  get fromId(): string
  get toId(): string
  get quantity(): number
  get namespace(): string | null
  setAttribute(key: string, valueJson: string): void
  getAttribute(key: string): string | null
  toString(): string
}
export declare class ResourceInstance {
  constructor(resourceId: string, entityId: string, namespace?: string | undefined | null)
  get id(): string
  get resourceId(): string
  get entityId(): string
  get namespace(): string | null
  setAttribute(key: string, valueJson: string): void
  getAttribute(key: string): string | null
  toString(): string
}
export declare class Instance {
  constructor(name: string, entityType: string, namespace?: string | undefined | null)
  get id(): string
  get name(): string
  get entityType(): string
  get namespace(): string | null
  setField(key: string, valueJson: string): void
  getField(key: string): string | null
  toString(): string
}
export declare class Metric {
  get name(): string
  get namespace(): string | null
  get threshold(): number | null
  get target(): number | null
  get unit(): string | null
  get severity(): string | null
}
export declare class Mapping {
  get name(): string
  get targetFormat(): string
}
export declare class Projection {
  get name(): string
  get targetFormat(): string
}
export declare class Role {
  constructor(name: string, namespace?: string | undefined | null)
  get id(): string
  get name(): string
  get namespace(): string | null
  setAttribute(key: string, valueJson: string): void
  getAttribute(key: string): string | null
  toString(): string
}
export declare class Relation {
  constructor(name: string, subjectRoleId: string, predicate: string, objectRoleId: string, namespace?: string | undefined | null, viaFlowId?: string | undefined | null)
  get id(): string
  get name(): string
  get subjectRoleId(): string
  get predicate(): string
  get objectRoleId(): string
  get viaFlowId(): string | null
  toString(): string
}
export declare class NamespaceBinding {
  constructor(path: string, namespace: string)
  get path(): string
  get namespace(): string
}
export declare class NamespaceRegistry {
  static fromFile(path: string): NamespaceRegistry
  static discover(path: string): Self | null
  resolveFiles(failOnAmbiguity?: boolean | undefined | null): Array<NamespaceBinding>
  namespaceFor(path: string, failOnAmbiguity?: boolean | undefined | null): string
  get root(): string
  get defaultNamespace(): string
}
export declare class Dimension {
  static parse(name: string): Dimension
  get name(): string
}
export declare class Unit {
  constructor(symbol: string, name: string, dimension: string, baseFactor: number, baseUnit: string)
  get symbol(): string
  get name(): string
  get dimension(): string
  get baseFactor(): number
  get baseUnit(): string
}
