// Root test entry point.
//
// The canonical napi build lives in domainforge-typescript/ (generated by
// `npm run build` / `bun run build`). typescript-tests import '../index', and
// `example.js` requires './index', so this file simply re-exports the canonical
// loader instead of duplicating it. This keeps a single source of truth and
// avoids drift between a root-level loader and the real package loader.
module.exports = require('./domainforge-typescript/index.js');
