/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Entity {
  constructor(name: string, namespace?: string | undefined | null)
  get id(): string
  get name(): string
  get namespace(): string | null
  setAttribute(key: string, valueJson: string): void
  getAttribute(key: string): string | null
  toString(): string
}
export declare class Resource {
  constructor(name: string, unit: string, namespace?: string | undefined | null)
  get id(): string
  get name(): string
  get unit(): string
  get namespace(): string | null
  setAttribute(key: string, valueJson: string): void
  getAttribute(key: string): string | null
  toString(): string
}
export declare class Flow {
  constructor(resourceId: string, fromId: string, toId: string, quantity: number)
  get id(): string
  get resourceId(): string
  get fromId(): string
  get toId(): string
  get quantity(): number
  get namespace(): string | null
  setAttribute(key: string, valueJson: string): void
  getAttribute(key: string): string | null
  toString(): string
}
export declare class Instance {
  constructor(resourceId: string, entityId: string, namespace?: string | undefined | null)
  get id(): string
  get resourceId(): string
  get entityId(): string
  get namespace(): string | null
  setAttribute(key: string, valueJson: string): void
  getAttribute(key: string): string | null
  toString(): string
}
export declare class Graph {
  constructor()
  addEntity(entity: Entity): void
  addResource(resource: Resource): void
  addFlow(flow: Flow): void
  addInstance(instance: Instance): void
  entityCount(): number
  resourceCount(): number
  flowCount(): number
  instanceCount(): number
  hasEntity(id: string): boolean
  hasResource(id: string): boolean
  hasFlow(id: string): boolean
  hasInstance(id: string): boolean
  getEntity(id: string): Entity | null
  getResource(id: string): Resource | null
  getFlow(id: string): Flow | null
  getInstance(id: string): Instance | null
  findEntityByName(name: string): string | null
  findResourceByName(name: string): string | null
  flowsFrom(entityId: string): Array<Flow>
  flowsTo(entityId: string): Array<Flow>
  allEntities(): Array<Entity>
  allResources(): Array<Resource>
  allFlows(): Array<Flow>
  allInstances(): Array<Instance>
  static parse(source: string): Graph
  exportCalm(): string
  static importCalm(calmJson: string): Graph
  toString(): string
}
