#!/usr/bin/env bash
# prove-canonical gate.
#
# Proves canonical determinism: the same .sea source, projected to a
# timestamp-pinned canonical directory projection (RDF/OWL) in two isolated
# working directories, produces BYTE-IDENTICAL output.
#
# This is the grounded determinism proof. The `rdf` projection is the canonical
# directory-output semantic representation and honours `--created-at` for
# byte-stable output (see `project --help`). We copy the fixture into two fresh
# mktemp dirs, project in each, and `diff -r` the results.
#
# Also asserts `pack build` fingerprint stability across two independent
# rebuilds (CLAIM-PACK-FINGERPRINT): Flow concept ids are content-addressable
# (domainforge-core/src/primitives/flow.rs), so source_graph_hash and
# meaning_fingerprint must be identical across isolated rebuilds of the same
# source.
#
# Writes evidence/latest/fragments/canonical.json. Invoked by
# `just prove-canonical`. Header conventions from tla.sh.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

CARGO_RUN=(cargo run -q -p domainforge-core --features cli --)
FRAG_DIR="evidence/latest/fragments"
mkdir -p "$FRAG_DIR"

FIXTURE="fixtures/projection_cell/basic/model.sea"
test -s "$FIXTURE" || { echo "canonical: missing $FIXTURE" >&2; exit 1; }

PINNED_TS="2026-01-01T00:00:00Z"

RUN1="$(mktemp -d)"
RUN2="$(mktemp -d)"
trap 'rm -rf "$RUN1" "$RUN2"' EXIT

# Two isolated runs: identical canonical input path, fresh independent output
# directories. Using the same input path keeps the run comparable — the only
# provenance difference the RDF projector can emit is a "# Generated ... from
# <path>" comment header, which we normalize below (documented exclusion in
# PROOFS.md CLAIM-DETERMINISM: the source-path provenance comment is excluded
# from byte comparison; all semantic triples are compared byte-for-byte).
echo "==> project --format rdf (run 1, pinned --created-at $PINNED_TS)"
"${CARGO_RUN[@]}" project --format rdf --created-at "$PINNED_TS" "$FIXTURE" "$RUN1/out"
echo "==> project --format rdf (run 2, pinned --created-at $PINNED_TS)"
"${CARGO_RUN[@]}" project --format rdf --created-at "$PINNED_TS" "$FIXTURE" "$RUN2/out"

echo "==> byte-compare RDF output directories (excluding source-path comment)"
norm() { find "$1" -type f | sort | sed "s#^$1/##"; }
# Structural: same set of files.
if ! diff <(norm "$RUN1/out") <(norm "$RUN2/out") >/dev/null; then
  echo "canonical: RDF projection produced a different file SET across runs" >&2
  diff <(norm "$RUN1/out") <(norm "$RUN2/out") >&2
  exit 1
fi
# Content: byte-identical after stripping the provenance "Generated ... from" line.
mismatch=0
while IFS= read -r rel; do
  a="$RUN1/out/$rel"; b="$RUN2/out/$rel"
  if ! diff \
      <(sed '/^# Generated by DomainForge/d' "$a") \
      <(sed '/^# Generated by DomainForge/d' "$b") >/dev/null; then
    echo "canonical: RDF file '$rel' differs across isolated runs (beyond provenance comment)" >&2
    diff <(sed '/^# Generated by DomainForge/d' "$a") \
         <(sed '/^# Generated by DomainForge/d' "$b") | head -40 >&2
    mismatch=1
  fi
done < <(norm "$RUN1/out")
if [[ $mismatch -ne 0 ]]; then exit 1; fi
echo "    RDF output byte-identical across two isolated runs OK"

echo "==> pack build (run 1 + run 2, independent) — fingerprint must be cross-run stable"
"${CARGO_RUN[@]}" pack build --source "$FIXTURE" --org acme \
  --domain procurement --version 1.0.0 --meaning-version 1.0.0 \
  --out "$RUN1/pack.json" >/dev/null 2>&1
"${CARGO_RUN[@]}" pack build --source "$FIXTURE" --org acme \
  --domain procurement --version 1.0.0 --meaning-version 1.0.0 \
  --out "$RUN2/pack.json" >/dev/null 2>&1

GRAPH_HASH_1="$(jq -r '.source_graph_hash // ""' "$RUN1/pack.json")"
GRAPH_HASH_2="$(jq -r '.source_graph_hash // ""' "$RUN2/pack.json")"
FP_1="$(jq -r '.meaning_fingerprint // ""' "$RUN1/pack.json")"
FP_2="$(jq -r '.meaning_fingerprint // ""' "$RUN2/pack.json")"

fingerprint_stable=false
if [[ -n "$GRAPH_HASH_1" && "$GRAPH_HASH_1" == "$GRAPH_HASH_2" && -n "$FP_1" && "$FP_1" == "$FP_2" ]]; then
  fingerprint_stable=true
  echo "    source_graph_hash and meaning_fingerprint identical across independent rebuilds OK"
else
  echo "canonical: pack build fingerprints differ across independent rebuilds" >&2
  echo "    graph_hash: $GRAPH_HASH_1 vs $GRAPH_HASH_2" >&2
  echo "    fingerprint: $FP_1 vs $FP_2" >&2
  exit 1
fi

cat > "$FRAG_DIR/canonical.json" <<JSON
{
  "canonical_determinism": {
    "passed": true,
    "runs_compared": 2,
    "projection": "rdf",
    "pinned_created_at": "$PINNED_TS",
    "byte_identical": true,
    "graph_hash": "$GRAPH_HASH_1",
    "fingerprint_stable_across_rebuilds": $fingerprint_stable,
    "meaning_fingerprint": "$FP_1"
  }
}
JSON

echo "==> prove-canonical OK"
