//! CMMN 1.1 projection: policies, roles, and resources project to a single,
//! XSD-valid CMMN 1.1 XML file (`--format cmmn`).
//!
//! Declared v1 subset (see `docs/cmmn-projections.md`): a case with case-file
//! items (from resources), case roles (from roles), human tasks (from entities),
//! milestones (from authority policies), and — the interesting part — sentries
//! whose entry criteria lower each policy's condition expression. Event
//! listeners are a **Non-goal v1**: the canonical model carries no runtime-event
//! source, so no `userEventListener` / `timerEventListener` is invented.
//!
//! One IR module ([`ir`]) + one renderer ([`xml`]) + one [`emit`] + one
//! [`project_cmmn_in_memory`] binding surface, per the shared projection pattern
//! (`projection/lean/mod.rs`), reusing the BPMN [`Xml`](xml) writer. Output is
//! byte-deterministic for a fixed `created_at`: every collection is sorted and
//! no wall-clock or random data enters file contents (the timestamp is
//! caller-supplied).

pub mod ir;
pub mod xml;

use crate::graph::Graph;
use crate::projection::sink::ArtifactSink;
use ir::CaseIR;
use std::collections::BTreeMap;

/// The single emitted artifact's relative path.
pub const OUTPUT_FILE: &str = "model.cmmn";

/// Emit the CMMN case into `sink`; returns the emitted relative paths.
pub fn emit(
    graph: &Graph,
    model_ref: &str,
    created_at: Option<String>,
    sink: &mut ArtifactSink,
) -> Result<Vec<String>, String> {
    let created_at = created_at.unwrap_or_else(|| chrono::Utc::now().to_rfc3339());
    let case = CaseIR::from_graph(graph, model_ref);
    // Self-check: never write a case with dangling IDREFs (the XSD cannot see
    // definitionRef/sentryRef/performerRef integrity — see validate_references).
    case.validate_references()?;

    let body = xml::render(&case);
    let content = with_provenance(&body, model_ref, &created_at);

    sink.write(OUTPUT_FILE, &content)?;
    Ok(vec![OUTPUT_FILE.to_string()])
}

/// Binding surface: string in, path→content map out, no filesystem.
pub fn project_cmmn_in_memory(
    graph: &Graph,
    model_ref: &str,
    created_at: Option<String>,
) -> Result<BTreeMap<String, String>, String> {
    let mut map = BTreeMap::new();
    let mut sink = ArtifactSink::Memory {
        prefix: String::new(),
        map: &mut map,
    };
    emit(graph, model_ref, created_at, &mut sink)?;
    Ok(map)
}

/// Insert a provenance XML comment directly after the XML declaration line.
/// `--` is illegal inside XML comments, so it is broken up.
fn with_provenance(body: &str, model_ref: &str, created_at: &str) -> String {
    let safe = |s: &str| s.replace("--", "- -").replace(['\n', '\r'], " ");
    let comment = format!(
        "<!-- Generated by DomainForge (format cmmn) from {}. Created: {}. Do not edit by hand. -->\n",
        safe(model_ref),
        safe(created_at)
    );
    match body.split_once('\n') {
        Some((decl, rest)) => format!("{decl}\n{comment}{rest}"),
        None => format!("{body}\n{comment}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse_to_graph;

    const FIXED_TS: &str = "2026-07-02T00:00:00+00:00";

    // A case with resources (→ case file items), roles (→ case roles), entities
    // (→ human tasks), and two policies whose conditions (→ sentries) gate two
    // milestones.
    const SOURCE: &str = r#"
@namespace "demo"

Entity "PurchaseOrder" in demo
Entity "Invoice" in demo

Role "Approver" in demo
Role "Clerk" in demo

Resource "Budget" units in demo

Policy positive_budget as: Budget.quantity > 0
Policy within_limit as: Budget.quantity < 500
"#;

    fn project(source: &str) -> BTreeMap<String, String> {
        let graph = parse_to_graph(source).expect("fixture parses");
        project_cmmn_in_memory(&graph, "test.sea", Some(FIXED_TS.to_string()))
            .expect("projection succeeds")
    }

    #[test]
    fn emits_single_cmmn_file() {
        let files = project(SOURCE);
        assert_eq!(files.keys().collect::<Vec<_>>(), vec!["model.cmmn"]);
    }

    #[test]
    fn contains_case_elements() {
        let cmmn = &project(SOURCE)["model.cmmn"];
        assert!(cmmn.contains("<definitions"));
        assert!(cmmn.contains("<case "));
        assert!(cmmn.contains("<casePlanModel"));
        assert!(cmmn.contains("<caseFileModel"));
        assert!(cmmn.contains("<caseFileItem"));
        assert!(cmmn.contains("name=\"Budget\"")); // case file item from resource
        assert!(cmmn.contains("<caseRoles"));
        assert!(cmmn.contains("name=\"Approver\"")); // case role
        assert!(cmmn.contains("<humanTask"));
        assert!(cmmn.contains("name=\"PurchaseOrder\"")); // human task from entity
        assert!(cmmn.contains("<milestone"));
        assert!(cmmn.contains("Generated by DomainForge"));
    }

    // The policy→sentry lowering: each policy condition becomes a sentry ifPart.
    #[test]
    fn policy_conditions_become_sentries() {
        let cmmn = &project(SOURCE)["model.cmmn"];
        assert!(cmmn.contains("<sentry"));
        assert!(cmmn.contains("<ifPart"));
        assert!(cmmn.contains("<condition"));
        // The policy expression text is embedded verbatim (escaped).
        assert!(cmmn.contains("Budget.quantity &gt; 0"));
        assert!(cmmn.contains("<entryCriterion"));
        assert!(cmmn.contains("sentryRef="));
    }

    // Teeth-check (unit level): removing the only policy removes the sentry.
    #[test]
    fn removing_the_policy_removes_the_sentry() {
        let with_policy = r#"
@namespace "demo"
Resource "Budget" units in demo
Policy positive_budget as: Budget.quantity > 0
"#;
        let without_policy = r#"
@namespace "demo"
Resource "Budget" units in demo
"#;
        let a = &project(with_policy)["model.cmmn"];
        let b = &project(without_policy)["model.cmmn"];
        assert!(a.contains("<sentry"), "policy must produce a sentry");
        assert!(a.contains("<milestone"), "policy must produce a milestone");
        assert!(
            !b.contains("<sentry"),
            "no policy must mean no sentry (teeth-check)"
        );
        assert!(!b.contains("<milestone"));
    }

    // When the graph binds a role to an entity, the entity's human task names
    // that role via performerRef (the `.sea` surface has no bind syntax, so this
    // is exercised through the graph API — future-proof wiring).
    #[test]
    fn bound_role_populates_performer_ref() {
        let mut graph = parse_to_graph(SOURCE).expect("parses");
        let role = graph.find_role_by_name("Approver").expect("role exists");
        let entity = graph
            .find_entity_by_name("PurchaseOrder")
            .expect("entity exists");
        graph
            .assign_role_to_entity(entity, role)
            .expect("assignment succeeds");
        let files = project_cmmn_in_memory(&graph, "test.sea", Some(FIXED_TS.to_string())).unwrap();
        assert!(files["model.cmmn"].contains("performerRef="));
    }

    #[test]
    fn empty_model_emits_minimal_case() {
        let cmmn = &project("@namespace \"empty\"\n")["model.cmmn"];
        assert!(cmmn.contains("<case "));
        assert!(cmmn.contains("<casePlanModel"));
        assert!(!cmmn.contains("<sentry"));
        assert!(!cmmn.contains("<humanTask"));
    }

    #[test]
    fn output_is_deterministic() {
        assert_eq!(project(SOURCE), project(SOURCE));
    }

    // Teeth-check: dropping a sentry leaves a dangling entryCriterion sentryRef
    // the CMMN XSD cannot catch, but the structural validator does.
    #[test]
    fn deleting_a_sentry_fails_structural_validation() {
        let graph = parse_to_graph(SOURCE).expect("parses");
        let mut ir = CaseIR::from_graph(&graph, "test.sea");
        ir.validate_references().expect("intact IR is valid");
        ir.sentries.pop().expect("has sentries");
        assert!(
            ir.validate_references().is_err(),
            "removing a sentry must break reference integrity"
        );
    }
}
