//! TypeScript DDD/CQRS renderer. Consumes [`crate::projection::domain::ir::DomainIr`]
//! and emits a complete, zero-runtime-dependency TypeScript package up to the port
//! boundary. `emit` = `DomainIr::from_graph` + pure render functions IR → TS source.
//! This renderer never touches [`crate::graph::Graph`].

use crate::graph::Graph;
use crate::projection::domain::ir::DomainIr;
use crate::projection::sink::ArtifactSink;
use std::collections::BTreeMap;

pub fn emit(
    graph: &Graph,
    model_ref: &str,
    created_at: Option<String>,
    sink: &mut ArtifactSink,
) -> Result<Vec<String>, String> {
    let ir = DomainIr::from_graph(graph)?;
    let created_at = created_at.unwrap_or_else(|| chrono::Utc::now().to_rfc3339());
    let files: Vec<(String, String)> = vec![
        ("package.json".to_string(), package_json(&ir)),
        ("tsconfig.json".to_string(), tsconfig()),
        ("README.md".to_string(), readme(&ir, model_ref, &created_at)),
        ("src/index.ts".to_string(), index_ts(&ir)),
        ("src/domain/valueObjects.ts".to_string(), value_objects(&ir)),
        ("src/domain/entities.ts".to_string(), entities(&ir)),
        ("src/domain/roles.ts".to_string(), roles(&ir)),
        ("src/domain/errors.ts".to_string(), errors(&ir)),
        ("src/domain/commands.ts".to_string(), commands(&ir)),
        ("src/domain/events.ts".to_string(), events(&ir)),
        ("src/domain/aggregates.ts".to_string(), aggregates(&ir)),
        ("src/ports/repositories.ts".to_string(), repositories(&ir)),
        ("src/ports/bus.ts".to_string(), bus(&ir)),
        ("src/ports/readModel.ts".to_string(), read_model(&ir)),
        ("src/container.ts".to_string(), container(&ir)),
        ("src/smoke.ts".to_string(), smoke(&ir)),
    ];
    let mut emitted = Vec::new();
    for (path, body) in &files {
        sink.write(path, body)?;
        emitted.push(path.clone());
    }
    Ok(emitted)
}

pub fn project_domain_typescript_in_memory(
    graph: &Graph,
    model_ref: &str,
    created_at: Option<String>,
) -> Result<BTreeMap<String, String>, String> {
    let mut map = BTreeMap::new();
    let mut sink = ArtifactSink::Memory {
        prefix: String::new(),
        map: &mut map,
    };
    emit(graph, model_ref, created_at, &mut sink)?;
    Ok(map)
}

// ---------- file renderers ----------

fn package_json(ir: &DomainIr) -> String {
    format!(
        r#"{{
  "name": "{pkg}-domain",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {{ "check": "tsc --noEmit" }},
  "devDependencies": {{ "typescript": "^5.0.0" }}
}}
"#,
        pkg = ir.package_slug
    )
}

fn tsconfig() -> String {
    r#"{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ES2022",
    "moduleResolution": "bundler",
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true
  },
  "include": ["src/**/*.ts"]
}
"#
    .to_string()
}

fn readme(ir: &DomainIr, model_ref: &str, created_at: &str) -> String {
    format!(
        "# {ns} domain package\n\nGenerated by DomainForge from `{model_ref}` at {created_at}.\n\n\
A complete, zero-runtime-dependency DDD/CQRS domain layer (TypeScript) up to the port\n\
boundary. Validate with `tsc --noEmit`.\n",
        ns = ir.namespace,
        model_ref = model_ref,
        created_at = created_at,
    )
}

fn index_ts(ir: &DomainIr) -> String {
    let mut s = String::from("export { Container } from \"./container\";\n");
    if !ir.entities.is_empty() {
        let names: Vec<&str> = ir.entities.iter().map(|e| e.name.as_str()).collect();
        s.push_str(&format!(
            "export {{ {} }} from \"./domain/entities\";\n",
            names.join(", ")
        ));
    }
    if !ir.aggregates.is_empty() {
        let names: Vec<&str> = ir.aggregates.iter().map(|a| a.name.as_str()).collect();
        s.push_str(&format!(
            "export {{ {} }} from \"./domain/aggregates\";\n",
            names.join(", ")
        ));
    }
    s.push_str("export { Quantity } from \"./domain/valueObjects\";\n");
    s.push_str("export { Role } from \"./domain/roles\";\n");
    s
}

fn value_objects(ir: &DomainIr) -> String {
    let mut s = String::new();
    if !ir.value_objects.is_empty() {
        let errs: Vec<String> = ir
            .value_objects
            .iter()
            .map(|v| v.error_name.clone())
            .collect();
        s.push_str(&format!(
            "import {{ {} }} from \"./errors\";\n\n",
            errs.join(", ")
        ));
    }
    s.push_str(
        "export class Quantity {\n  readonly amount: number;\n  readonly unit: string;\n  constructor(amount: number, unit: string) {\n    this.amount = amount;\n    this.unit = unit;\n  }\n}\n",
    );
    for vo in &ir.value_objects {
        s.push_str(&format!(
            "\nexport class {name} {{\n  readonly value: string;\n  constructor(value: string) {{\n    if (!/{regex}/.test(value)) {{\n      throw new {err}(value);\n    }}\n    this.value = value;\n  }}\n}}\n",
            name = vo.name,
            regex = vo.regex.replace('/', "\\/"),
            err = vo.error_name
        ));
    }
    s
}

fn entities(ir: &DomainIr) -> String {
    let mut s = String::new();
    for e in &ir.entities {
        let fields: Vec<String> = e
            .fields
            .iter()
            .map(|(n, _)| format!("  readonly {n}: string | null;"))
            .collect();
        let field_block = if fields.is_empty() {
            String::new()
        } else {
            format!("\n{}", fields.join("\n"))
        };
        s.push_str(&format!(
            "export class {name} {{\n  readonly id: string;\n  readonly name: string;{fields}\n  constructor(id: string, name: string{ctor}) {{\n    this.id = id;\n    this.name = name;{assign}\n  }}\n}}\n\n",
            name = e.name,
            fields = field_block,
            ctor = e.fields.iter().map(|(n, _)| format!(", {n}: string | null = null")).collect::<String>(),
            assign = e.fields.iter().map(|(n, _)| format!("\n    this.{n} = {n};")).collect::<String>(),
        ));
    }
    s
}

fn roles(ir: &DomainIr) -> String {
    let variants: Vec<String> = ir
        .roles
        .iter()
        .map(|r| format!("  {r} = \"{r}\""))
        .collect();
    let mut s = format!("export enum Role {{\n{}\n}}\n", variants.join(",\n"));
    if !ir.relations_doc.is_empty() {
        s.push_str("\n// Relations:\n");
        for line in &ir.relations_doc {
            s.push_str(&format!("// {line}\n"));
        }
    }
    s
}

fn errors(ir: &DomainIr) -> String {
    let mut s = String::from(
        "export class DomainError extends Error {\n  constructor(message: string) {\n    super(message);\n    this.name = \"DomainError\";\n  }\n}\n",
    );
    for e in &ir.errors {
        let doc = e.rationale.as_deref().unwrap_or("Policy violation.");
        s.push_str(&format!(
            "\n/** {doc} */\nexport class {name} extends DomainError {{\n  constructor() {{\n    super(\"{name}\");\n    this.name = \"{name}\";\n  }}\n}}\n",
            name = e.name,
            doc = doc
        ));
    }
    for vo in &ir.value_objects {
        s.push_str(&format!(
            "\n/** Value object validation error. */\nexport class {err} extends DomainError {{\n  constructor(value: string) {{\n    super(`Invalid {vo}: ${{value}}`);\n    this.name = \"{err}\";\n  }}\n}}\n",
            err = vo.error_name,
            vo = vo.name
        ));
    }
    s
}

fn commands(ir: &DomainIr) -> String {
    let mut s = String::from(
        "import { Role } from \"./roles\";\nimport { Quantity } from \"./valueObjects\";\n",
    );
    for c in &ir.commands {
        s.push_str(&format!(
            "\nexport interface {name} {{\n  readonly kind: \"{name}\";\n  readonly aggregate_id: string;\n  readonly quantity: Quantity;\n  readonly issued_by: Role;\n}}\n",
            name = c.name
        ));
    }
    s.push('\n');
    if ir.commands.is_empty() {
        s.push_str("export type Command = never;\n");
    } else {
        let names: Vec<String> = ir.commands.iter().map(|c| c.name.clone()).collect();
        s.push_str(&format!("export type Command = {};\n", names.join(" | ")));
    }
    s
}

fn events(ir: &DomainIr) -> String {
    let mut s = String::from("import { Quantity } from \"./valueObjects\";\n");
    for e in &ir.events {
        s.push_str(&format!(
            "\nexport interface {name} {{\n  readonly kind: \"{name}\";\n  readonly aggregate_id: string;\n  readonly quantity: Quantity;\n  readonly occurred_at: string;\n}}\n",
            name = e.name
        ));
    }
    s.push('\n');
    if ir.events.is_empty() {
        s.push_str("export type DomainEvent = never;\n");
    } else {
        let names: Vec<String> = ir.events.iter().map(|e| e.name.clone()).collect();
        s.push_str(&format!(
            "export type DomainEvent = {};\n",
            names.join(" | ")
        ));
    }
    s
}

fn aggregates(ir: &DomainIr) -> String {
    let mut s = String::from(
        "import { Role } from \"./roles\";\nimport { Quantity } from \"./valueObjects\";\n",
    );
    let event_names: Vec<String> = ir.events.iter().map(|e| e.name.clone()).collect();
    if !event_names.is_empty() {
        s.push_str(&format!(
            "import {{ {} }} from \"./events\";\n",
            event_names.join(", ")
        ));
    }
    for agg in &ir.aggregates {
        s.push_str(&format!(
            "\nexport class {name} {{\n  readonly id: string;\n  readonly name: string;\n  constructor(id: string, name: string) {{\n    this.id = id;\n    this.name = name;\n  }}\n",
            name = agg.name
        ));
        for m in &agg.methods {
            match &m.event {
                Some(ret) => s.push_str(&format!(
                    "  {cname}(quantity: Quantity, issuedBy: Role, occurredAt: string): {ret} {{\n{guards}    return {{ kind: \"{ret}\", aggregate_id: this.id, quantity, occurred_at: occurredAt }};\n  }}\n",
                    cname = camel(&m.name),
                    ret = ret,
                    guards = m.guard_checks.iter().map(|g| format!("    this.{}();\n", camel(&g.check_method))).collect::<String>()
                )),
                None => s.push_str(&format!(
                    "  {cname}(quantity: Quantity, issuedBy: Role): void {{\n{guards}    return;\n  }}\n",
                    cname = camel(&m.name),
                    guards = m.guard_checks.iter().map(|g| format!("    this.{}();\n", camel(&g.check_method))).collect::<String>()
                )),
            }
        }
        // Guard hooks (no-op in v1).
        let mut seen: Vec<String> = Vec::new();
        for g in agg.methods.iter().flat_map(|m| m.guard_checks.iter()) {
            if seen.contains(&g.check_method) {
                continue;
            }
            seen.push(g.check_method.clone());
            let rationale = ir
                .errors
                .iter()
                .find(|e| e.name == g.error)
                .and_then(|e| e.rationale.clone())
                .unwrap_or_else(|| "Policy guard.".to_string());
            s.push_str(&format!(
                "  /** {rationale} */\n  {c}(): void {{ return; }}\n",
                c = camel(&g.check_method),
                rationale = rationale
            ));
        }
        s.push_str("}\n");
    }
    s
}

fn repositories(ir: &DomainIr) -> String {
    let names: Vec<String> = ir.aggregates.iter().map(|a| a.name.clone()).collect();
    let mut s = String::new();
    if !names.is_empty() {
        s.push_str(&format!(
            "import {{ {} }} from \"../domain/aggregates\";\n",
            names.join(", ")
        ));
    }
    for agg in &ir.aggregates {
        s.push_str(&format!(
            "\nexport interface {name}Repository {{\n  get(id: string): Promise<{name} | null>;\n  save(aggregate: {name}): Promise<void>;\n}}\n",
            name = agg.name
        ));
    }
    s
}

fn bus(_ir: &DomainIr) -> String {
    "import { Command } from \"../domain/commands\";\nimport { DomainEvent } from \"../domain/events\";\n\n\
export interface EventBus {\n  publish(event: DomainEvent): Promise<void>;\n}\n\n\
export interface CommandBus {\n  dispatch(command: Command): Promise<void>;\n}\n"
        .to_string()
}

fn read_model(ir: &DomainIr) -> String {
    let mut s = String::new();
    if !ir.queries.is_empty() {
        s.push_str("import { Quantity } from \"../domain/valueObjects\";\n");
    }
    s.push_str(&format!(
        "\nexport interface {ns}ReadModel {{\n",
        ns = ir.package_pascal
    ));
    for q in &ir.queries {
        let mut doc = format!("Metric '{}'", q.metric_name);
        if let Some(u) = &q.unit {
            doc.push_str(&format!(" (unit: {u})"));
        }
        if let Some(t) = &q.threshold {
            doc.push_str(&format!(", threshold: {t}"));
        }
        doc.push('.');
        s.push_str(&format!(
            "  /** {doc} */\n  {mname}(): Quantity;\n",
            doc = doc,
            mname = q.name
        ));
    }
    s.push_str("}\n");
    s
}

fn container(ir: &DomainIr) -> String {
    let mut s = String::new();
    s.push_str("import { EventBus, CommandBus } from \"./ports/bus\";\n");
    s.push_str(&format!(
        "import {{ {}ReadModel }} from \"./ports/readModel\";\n",
        ir.package_pascal
    ));
    if !ir.aggregates.is_empty() {
        let names: Vec<String> = ir
            .aggregates
            .iter()
            .map(|a| format!("{}Repository", a.name))
            .collect();
        s.push_str(&format!(
            "import {{ {} }} from \"./ports/repositories\";\n",
            names.join(", ")
        ));
    }
    let mut fields: Vec<String> = ir
        .aggregates
        .iter()
        .map(|a| {
            format!(
                "  readonly {}: {}Repository;",
                to_lower_first(&a.name),
                a.name
            )
        })
        .collect();
    fields.push("  readonly eventBus: EventBus;".to_string());
    fields.push("  readonly commandBus: CommandBus;".to_string());
    fields.push(format!(
        "  readonly readModel: {}ReadModel;",
        ir.package_pascal
    ));
    s.push_str(&format!(
        "\nexport interface Container {{\n{}\n}}\n",
        fields.join("\n")
    ));
    s
}

fn smoke(ir: &DomainIr) -> String {
    let mut s = String::from("import { Quantity } from \"./domain/valueObjects\";\n");
    s.push_str("import { Role } from \"./domain/roles\";\n");
    if !ir.commands.is_empty() {
        s.push_str("import { type Command } from \"./domain/commands\";\n");
    }
    if !ir.events.is_empty() {
        s.push_str("import { type DomainEvent } from \"./domain/events\";\n");
    }
    for vo in &ir.value_objects {
        s.push_str(&format!(
            "import {{ {vo} }} from \"./domain/valueObjects\";\n",
            vo = vo.name
        ));
    }
    s.push_str("\nfunction assert(condition: unknown): asserts condition {\n  if (!condition) {\n    throw new Error(\"assertion failed\");\n  }\n}\n\n");
    s.push_str("// Compile-time + runtime exercise of every construct.\n");
    for c in &ir.commands {
        s.push_str(&format!(
            "const cmd{n}: Command = {{ kind: \"{n}\", aggregate_id: \"a\", quantity: new Quantity(1, \"u\"), issued_by: Role.{role} }};\nassert(cmd{n}.aggregate_id === \"a\");\n",
            n = c.name,
            role = ir.roles.first().cloned().unwrap_or_else(|| "Requester".to_string())
        ));
    }
    for e in &ir.events {
        s.push_str(&format!(
            "const ev{n}: DomainEvent = {{ kind: \"{n}\", aggregate_id: \"a\", quantity: new Quantity(1, \"u\"), occurred_at: \"now\" }};\nassert(ev{n}.occurred_at === \"now\");\n",
            n = e.name
        ));
    }
    for vo in &ir.value_objects {
        s.push_str(&format!(
            "const good{vo} = new {vo}(\"ABC-1\");\nassert(good{vo}.value === \"ABC-1\");\n",
            vo = vo.name
        ));
    }
    s
}

// ---------- helpers ----------

/// Convert a snake_case identifier to camelCase (TS method convention).
fn camel(snake: &str) -> String {
    let mut out = String::new();
    let mut up = false;
    for ch in snake.chars() {
        if ch == '_' {
            up = true;
        } else if up {
            out.push(ch.to_ascii_uppercase());
            up = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn to_lower_first(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        Some(first) => first.to_ascii_lowercase().to_string() + c.as_str(),
        None => String::new(),
    }
}

/// Temporary helper so `aggregates()` can reference the method name cleanly;
/// returns the snake_case method name (camel is applied at the call site).
#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse_to_graph;

    const FIXED_TS: &str = "2026-07-02T00:00:00+00:00";

    fn fixture_files() -> BTreeMap<String, String> {
        let src = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../fixtures/projection_cell/basic/model.sea"),
        )
        .expect("fixture");
        let graph = parse_to_graph(&src).expect("parses");
        project_domain_typescript_in_memory(&graph, "test.sea", Some(FIXED_TS.to_string()))
            .expect("projects")
    }

    #[test]
    fn emits_expected_file_set() {
        let files = fixture_files();
        let keys: Vec<&str> = files.keys().map(|s| s.as_str()).collect();
        assert!(keys.contains(&"package.json"), "missing package.json");
        assert!(keys.contains(&"tsconfig.json"), "missing tsconfig.json");
        assert!(
            keys.contains(&"src/domain/aggregates.ts"),
            "missing aggregates"
        );
        assert!(
            keys.contains(&"src/ports/repositories.ts"),
            "missing repositories"
        );
        assert!(keys.contains(&"src/smoke.ts"), "missing smoke");
    }

    #[test]
    fn key_content_present() {
        let files = fixture_files();
        let repos = &files["src/ports/repositories.ts"];
        assert!(
            repos.contains("interface PurchaseOrderRepository"),
            "missing PurchaseOrderRepository"
        );
        let errs = &files["src/domain/errors.ts"];
        assert!(
            errs.contains("class RequireApprovalViolation extends DomainError"),
            "missing error"
        );
    }

    #[test]
    fn deterministic() {
        assert_eq!(fixture_files(), fixture_files());
    }

    #[test]
    fn zero_runtime_deps() {
        let files = fixture_files();
        let pj = &files["package.json"];
        assert!(pj.contains("\"private\": true"), "must be private");
        assert!(
            !pj.contains("\"dependencies\""),
            "must declare no runtime dependencies"
        );
    }
}
