/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'domainforge-core.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./domainforge-core.android-arm64.node')
          } else {
            nativeBinding = require('domainforge-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'domainforge-core.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./domainforge-core.android-arm-eabi.node')
          } else {
            nativeBinding = require('domainforge-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'domainforge-core.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./domainforge-core.win32-x64-msvc.node')
          } else {
            nativeBinding = require('domainforge-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'domainforge-core.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./domainforge-core.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('domainforge-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'domainforge-core.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./domainforge-core.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('domainforge-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'domainforge-core.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./domainforge-core.darwin-universal.node')
      } else {
        nativeBinding = require('domainforge-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'domainforge-core.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./domainforge-core.darwin-x64.node')
          } else {
            nativeBinding = require('domainforge-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'domainforge-core.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./domainforge-core.darwin-arm64.node')
          } else {
            nativeBinding = require('domainforge-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'domainforge-core.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./domainforge-core.freebsd-x64.node')
      } else {
        nativeBinding = require('domainforge-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'domainforge-core.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./domainforge-core.linux-x64-musl.node')
            } else {
              nativeBinding = require('domainforge-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'domainforge-core.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./domainforge-core.linux-x64-gnu.node')
            } else {
              nativeBinding = require('domainforge-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'domainforge-core.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./domainforge-core.linux-arm64-musl.node')
            } else {
              nativeBinding = require('domainforge-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'domainforge-core.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./domainforge-core.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('domainforge-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'domainforge-core.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./domainforge-core.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('domainforge-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'domainforge-core.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./domainforge-core.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('domainforge-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'domainforge-core.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./domainforge-core.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('domainforge-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'domainforge-core.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./domainforge-core.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('domainforge-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'domainforge-core.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./domainforge-core.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('domainforge-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { FinalDecision, PolicyModality, SourceClass, ClaimLevel, evaluateAuthority, formatSource, checkFormat, Graph, AggregateFunction, BinaryOp, UnaryOp, Quantifier, Severity, Expression, NormalizedExpression, Entity, Resource, Flow, ResourceInstance, Instance, Metric, Mapping, Projection, Role, Relation, NamespaceBinding, NamespaceRegistry, SemanticTruth, DiagnosticSeverity, ValidationMode, ApprovalState, SignatureState, ConceptStatus, ConceptKind, AliasStatus, SemanticValidationStatus, semanticPackBuild, semanticPackValidate, semanticPackValidateGraph, semanticPackSign, semanticPackVerify, semanticPackDiff, semanticPackHash, semanticNormalizeKey, semanticResolveConcept, Dimension, Unit } = nativeBinding

module.exports.FinalDecision = FinalDecision
module.exports.PolicyModality = PolicyModality
module.exports.SourceClass = SourceClass
module.exports.ClaimLevel = ClaimLevel
module.exports.evaluateAuthority = evaluateAuthority
module.exports.formatSource = formatSource
module.exports.checkFormat = checkFormat
module.exports.Graph = Graph
module.exports.AggregateFunction = AggregateFunction
module.exports.BinaryOp = BinaryOp
module.exports.UnaryOp = UnaryOp
module.exports.Quantifier = Quantifier
module.exports.Severity = Severity
module.exports.Expression = Expression
module.exports.NormalizedExpression = NormalizedExpression
module.exports.Entity = Entity
module.exports.Resource = Resource
module.exports.Flow = Flow
module.exports.ResourceInstance = ResourceInstance
module.exports.Instance = Instance
module.exports.Metric = Metric
module.exports.Mapping = Mapping
module.exports.Projection = Projection
module.exports.Role = Role
module.exports.Relation = Relation
module.exports.NamespaceBinding = NamespaceBinding
module.exports.NamespaceRegistry = NamespaceRegistry
module.exports.SemanticTruth = SemanticTruth
module.exports.DiagnosticSeverity = DiagnosticSeverity
module.exports.ValidationMode = ValidationMode
module.exports.ApprovalState = ApprovalState
module.exports.SignatureState = SignatureState
module.exports.ConceptStatus = ConceptStatus
module.exports.ConceptKind = ConceptKind
module.exports.AliasStatus = AliasStatus
module.exports.SemanticValidationStatus = SemanticValidationStatus
module.exports.semanticPackBuild = semanticPackBuild
module.exports.semanticPackValidate = semanticPackValidate
module.exports.semanticPackValidateGraph = semanticPackValidateGraph
module.exports.semanticPackSign = semanticPackSign
module.exports.semanticPackVerify = semanticPackVerify
module.exports.semanticPackDiff = semanticPackDiff
module.exports.semanticPackHash = semanticPackHash
module.exports.semanticNormalizeKey = semanticNormalizeKey
module.exports.semanticResolveConcept = semanticResolveConcept
module.exports.Dimension = Dimension
module.exports.Unit = Unit
